### ISSUE TITLE
Incorrect reference to ecos repository while doing git submodule update

### ISSUE THREAD

**Issue by hurak** [embotech/ecos-matlab#4]
While doing 
`git submodule update`
I get 
`error: no such remote ref 51223ef6f4d9290c00f08fc9d7f1f0a02fabd161`
To see what is going on, I cloned the actual ecos repository and then I do
`git checkout 51223ef6f4d9290c00f08fc9d7f1f0a02fabd161` 
and get
`fatal: reference is not a tree: 51223ef6f4d9290c00f08fc9d7f1f0a02fabd161`

**Comment by yvaine** [comment]
same bug

**Comment by gminorcoles** [comment]
me too

**Comment by gminorcoles** [comment]
so I forced this to seemngly work by deleting the ecos subdirectory under ecos-matlab and then I just did git clone https://github.com/embotech/ecos.git, from the ecos-matlab directory. then in matlab I went to ecos-matlab/bin and ran makemex from matlab, and then after that yalmiptest reported that ECOS solved the problems in the test suite that it was supposed to solve, and declared the infeasible ones infeasible

**Comment by smerkli** [comment]
That commit seems to have gone missing, I'll investigate. For anyone seeing this before the fix comes around, if you have a new enough version of git you can do 
```
git submodule update --recursive --init --remote
```
The `--remote` part is what makes git get the newest state of the submodule from the remote instead of the commit in place.
