### ISSUE TITLE
ECOS YALMIP SUPPORT

### ISSUE THREAD

**Issue by onurgurisik** [embotech/ecos-matlab#5]
I need to use ecos solver with yalmip. I downloaded and set all paths in Matlab. When I run yalmiptest.m , ECOS is shown as founded. But at end of the test I got this messages as follows.

| SOCP| N/A| Unknown problem in solver (Turn on 'debug' in sdpsettings) (Attempt to execute SCRIPT ecos as a function:
C:\Users\user\Documents\MATLAB\ecos-matlab-master\bin\ecos.m)|
| SOCP| N/A| Unknown problem in solver (Turn on 'debug' in sdpsettings) (Attempt to execute SCRIPT ecos as a function:
C:\Users\user\Documents\MATLAB\ecos-matlab-master\bin\ecos.m)|
| SOCP| N/A| Unknown problem in solver (Turn on 'debug' in sdpsettings) (Attempt to execute SCRIPT ecos as a function:
C:\Users\user\Documents\MATLAB\ecos-matlab-master\bin\ecos.m)|

**Comment by onurgurisik** [comment]
Yalmip interface tries to run ecos.m script. But, when I look ecos.m file under the directory of /ecos-matlab/bin, I realized that all context is commented. I believe that it causes to the problem.

**Comment by gdominguezcala** [comment]
Hi @onurgurisik. I am having the same issue but by running ecos directly in Matlab. It looks like there is no code inside ecos.m, only the descriptive header. Did you manage to solve it?

**Comment by adomahidi** [comment]
You need to first build the mex file. Have you run `makemex.m`?

**Comment by gdominguezcala** [comment]
Thank you for the reply. Yes, I found the issue. It was building the mex file in another folder (inside matlab/ecos), but detecting the empty descriptive header file in (matlab/bin). By renaming and targeting the built ecos file I was able to run it in CVX and in Matlab.

**Comment by adomahidi** [comment]
You shouldn't need to rename, if `ecos.m` and `ecos.mexw64` is in the same directory, Matlab will run the mex file but you can still do a `help ecos`

**Comment by adomahidi** [comment]
If it doesn't work out of the box please feel free to submit a PR with a fix - otherwise I'll close this issue

**Comment by gdominguezcala** [comment]
I just moved ecos.m to the directory where ecos.mexw64 is and it is running with the help function as expected. Thank you for your help. You can close the issue.
